dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        maven {
            url "https://repo1.maven.org/maven2"
        }
        maven {
            url "https://jitpack.io"
        }
    }
}

include ':app'

apply from: 'capacitor.settings.gradle'
